#ifndef PIVX_CHAINPARAMSSEEDS_H
#define PIVX_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Rupaya network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 * Format: 0x01 (IPv4) | 0x04 | 4-byte-IP | 2-byte-port (big-endian)
 *         0x02 (IPv6) | 0x10 | 16-byte-IP | 2-byte-port (big-endian)
 *         0x04 (Tor)  | addr-len | addr | 2-byte-port
 *
 * TODO: Replace 127.0.0.1 placeholders with real Rupaya seed node IPs
 *       (both IPv4 and IPv6) once nodes are deployed.
 *       Regenerate with: python3 contrib/seeds/generate-seeds.py
 */
static const uint8_t chainparams_seed_main[] = {
    // IPv4: 127.0.0.1:8765 (placeholder — replace with real seed nodes)
    0x01,0x04,0x7f,0x00,0x00,0x01,0x22,0x4d,
};

static const uint8_t chainparams_seed_test[] = {
    // IPv4: 127.0.0.1:8766 (placeholder — replace with real testnet seed nodes)
    0x01,0x04,0x7f,0x00,0x00,0x01,0x22,0x4e,
};

#endif // PIVX_CHAINPARAMSSEEDS_H
